### ISSUE TITLE
This repository is dead

### ISSUE THREAD

**Issue by HVR88** [Ape/samsungctl#130]
Move along, the software doesn't work for up to date TVs and is no longer being maintained.

**Comment by luisalvarado** [comment]
Super dead. I tried 3 TVs. One 8500 from 2016, another 2018 Q9FN and another 6290 from 2019. None of them work. I doubt it actually worked in the first place since it fails even on 2016 ones and up.

**Comment by iminet** [comment]
That's the problem if you skip anything's official way and you turn to 3rd party solutions. You never can be sure, the project owner won't leave alone. This is a risky way, sadly.
Github is full of great stuff, but a lot of already are dead.

If I were Github staff, I'd bind project owners to get their projects ceased in a good way and archive the project. There's no sign this project is dead, it seems, it is still under development. This is the betrayal of the users.

@Ape please inform your users properly, maintain **or** archive the project, otherwise we'll report you at Github.
If you earned your users' trust, that's so unfair if you leave them without a word.

**Comment by HVR88** [comment]
https://github.com/tavicu/homebridge-samsung-tizen

The above is the ONLY active project I know of for any platform that can control most Samsung TVs. Unfortunately it's not a replacement for this project.
